version: '3'

services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
          
    ports:
      - "9999:9999"
